site_name: Boise State Research Computing
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: docs/images/boisestate-B-2color-rgb.png
  favicon: docs/images/boisestate-B-2color-rgb.png
  palette:
    scheme: bsu
