site_name: Boise State Research Computing
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: images/boisestate-B-1color-orange-rgb.png
  favicon: images/boisestate-B-1color-orange-rgb.png
  palette:
    scheme: bsu
