site_name: Boise State Research Computing
theme:
  name: material
  logo: images/boisestate-B-1color-orange-rgb.png
  favicon: images/boisestate-B-1color-orange-rgb.png
  palette:
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
