site_name: Boise State Research Computing
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: images/boisestate-B-1color-orange-rgb.png
  favicon: images/boisestate-B-1color-orange-rgb.png
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: bsu
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: bsu
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
